### ISSUE TITLE
rust-sysfs-pwm is not on cargo

### ISSUE THREAD

**Issue by cwoodall** [rust-embedded/rust-sysfs-pwm#1]
Hello @posborne  I noticed this package was not on crates.io. 

What is the path forward for that, if there is one? Currently I am using cargo's ability to install packages using git urls, but I think this would be useful to more people eventually.

**Comment by posborne** [comment]
Huh, I must have just forgotten to do that with everything else.  I'll probably move this to rust-embedded and publish 0.1.

**Comment by posborne** [comment]
Done: https://crates.io/crates/sysfs-pwm

**Comment by cwoodall** [comment]
Thanks! Just noticed when I was playing around with it. Worked perfectly on my beaglebone (once I figured out the chip to pin mapping)

**Comment by posborne** [comment]
On the pin mapping, this might be useful as a reference: https://github.com/rust-embedded/gpio-utils/blob/master/examples/beaglebone.toml
